// GENERATED by gen-diverse-epics.mjs — do not hand-edit; change the template in epics-src/<topology>.mjs instead.
// Independent property-based grader for the quota-d1 epic. Thin wrapper over the shared template
// builder in ../../epics-src/quota.mjs (the SAME grader the validity gate self-tests at ≥ K6).
import { buildQuotaOracle, walletDomainsFor } from '../../epics-src/quota.mjs';

const o = buildQuotaOracle(walletDomainsFor(1));
export const EXPECTS = o.EXPECTS;
export const happy = o.happy;
export const crosscut = o.crosscut;
export const integration = o.integration;
