// GENERATED by gen-diverse-epics.mjs — do not hand-edit; change the template in epics-src/<topology>.mjs instead.
// Independent property-based grader for the approval-d4 epic. Thin wrapper over the shared template
// builder in ../../epics-src/approval.mjs (the SAME grader the validity gate self-tests at ≥ K6).
import { buildApprovalOracle, requestDomainsFor } from '../../epics-src/approval.mjs';

const o = buildApprovalOracle(requestDomainsFor(4));
export const EXPECTS = o.EXPECTS;
export const happy = o.happy;
export const crosscut = o.crosscut;
export const integration = o.integration;
