#!/usr/bin/env node
// M-coh-3 (SIZE × HARNESS): generate a SCALABLE epic fixture `epics/scale-d<D>/` from the domain catalog
// in lib/scale-oracle.mjs. Each fixture is the SAME kind of multi-tenant epic at a different SIZE (D
// domains = 4D+1 surfaces), so the existing harness (`epic-run.mjs --epic scale-d<D>`) can run the size
// ladder with no core change. The hidden cross-cutting obligations live ONLY in skeleton.md (the frozen
// contract); the surface specs and preamble state happy-path + db field names only — identical trap to the
// workspace fixture, so a bare condition must invent the per-domain membership shape (drift) and the
// hidden guards (fragmentation), and those failure surfaces GROW with D.
//
// Run:
//   node studies/build-gap/gen-epic.mjs            # writes scale-d1 .. scale-d<MAX>
//   node studies/build-gap/gen-epic.mjs --max 4    # writes scale-d1 .. scale-d4
//
// The output is committed so a reviewer can run the harness without first running this. Re-running is
// idempotent. Each generated file carries a "GENERATED by gen-epic.mjs" header.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { DOMAIN_CATALOG, MAX_DOMAINS, domainsFor } from './lib/scale-oracle.mjs';

const arg = (name, def) => {
  const i = process.argv.indexOf(`--${name}`);
  if (i !== -1 && process.argv[i + 1]) return process.argv[i + 1];
  return def;
};
const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const GEN = '<!-- GENERATED by gen-epic.mjs — do not hand-edit; change the template/catalog instead. -->';

function preamble(domains) {
  const lines = [];
  lines.push('All functions share one context object `ctx`:', '');
  lines.push("- `ctx.session` — the authenticated caller: `{ userId, orgId, role }`, where `role` is `'member'` or `'admin'`.");
  lines.push('- `ctx.db.users` — a Map from userId (string) to a user record `{ id, orgId, name, bio, role }`.');
  for (const d of domains) {
    lines.push(`- \`ctx.db.${d.containersDb}\` — a Map from ${d.idArg} (string) to a ${d.containerWord} record \`{ id, orgId, name }\`.`);
    lines.push(`- \`ctx.db.${d.leavesDb}\` — an array of ${d.leafWord} records, each \`{ id, ${d.idArg}, authorId, orgId, body, createdAt }\`.`);
  }
  lines.push('');
  lines.push('The system is multi-tenant: every record belongs to an organization (`orgId`).');
  return lines.join('\n') + '\n';
}

function skeleton(domains) {
  const lines = [];
  lines.push('## Shared contract (frozen — every surface MUST conform to this)', '');
  lines.push('These decisions are fixed for the whole epic so the independently-built surfaces compose. Do not');
  lines.push('invent your own variants.', '');
  lines.push('### Shared data shapes');
  for (const d of domains) {
    lines.push(`- **${d.containerWord[0].toUpperCase() + d.containerWord.slice(1)} membership lives in \`ctx.db.${d.membersDb}\`** — an array of records ` +
      `\`{ ${d.idArg}, userId, role }\`. One record per (${d.containerWord}, user). To add a membership, push such a ` +
      `record (replacing any existing record for the same ${d.containerWord}+user). To test whether a user is a member, ` +
      `look for a matching record in \`ctx.db.${d.membersDb}\`. If it is undefined, treat it as an empty array and create it.`);
  }
  lines.push(`- ${domains.map((d) => `${d.containerWord} records are \`{ id, orgId, name }\` in \`ctx.db.${d.containersDb}\``).join('; ')}.`);
  lines.push(`- ${domains.map((d) => `${d.leafWord} records are \`{ id, ${d.idArg}, authorId, orgId, body, createdAt }\` in \`ctx.db.${d.leavesDb}\``).join('; ')}.`);
  lines.push('- New ids are unique non-empty strings.', '');
  lines.push('### Cross-cutting rules (apply on EVERY surface they touch)');
  lines.push('- **Tenancy:** a caller may only read or write records belonging to their own `ctx.session.orgId`. New');
  lines.push("  records are stamped with the caller's `orgId`, never a client-supplied one. A read (e.g. listing)");
  lines.push('  returns only the caller-org records. Operating across orgs throws.');
  lines.push('- **Authorization:** every `add…Member` requires the caller to be an `admin`. Every `post…` requires the');
  lines.push('  caller to be a member of that container. `updateProfile` requires the caller to be the target user or');
  lines.push('  an admin.');
  lines.push('- **No mass-assignment:** `updateProfile` may change only `name` and `bio`; it must never let `patch` set');
  lines.push('  `id`, `orgId`, or `role`.');
  return lines.join('\n') + '\n';
}

// ---- per-surface happy-path-only specs (the obligations stay hidden) ----
const surfaceSpec = {
  create: (d) => `Implement ${d.containerWord} creation.

Write an ES module that exports a function:

  export function ${d.createFn}(ctx, input) { ... }

- \`input\` is \`{ name }\`.
- Create a new ${d.containerWord} record and add it to \`ctx.db.${d.containersDb}\`, keyed by a new unique string id.
- Return the created ${d.containerWord} record.

Return ONLY the JavaScript module code. No prose, no markdown.
`,
  list: (d) => `Implement listing ${d.containerWord}s.

Write an ES module that exports a function:

  export function ${d.listFn}(ctx) { ... }

- Return an array of the ${d.containerWord} records in \`ctx.db.${d.containersDb}\`.

Return ONLY the JavaScript module code. No prose, no markdown.
`,
  addMember: (d) => `Implement adding a member to a ${d.containerWord}.

Write an ES module that exports a function:

  export function ${d.addMemberFn}(ctx, ${d.idArg}, userId, role) { ... }

- Record that the user \`userId\` is a member of the ${d.containerWord} \`${d.idArg}\`, with the given \`role\`
  (\`'member'\` or \`'admin'\`).
- Return the created membership.
- If the ${d.containerWord} or the user does not exist, throw an Error.

Return ONLY the JavaScript module code. No prose, no markdown.
`,
  post: (d) => `Implement posting a ${d.leafWord} on a ${d.containerWord}.

Write an ES module that exports a function:

  export function ${d.postFn}(ctx, ${d.idArg}, body) { ... }

- Append a new ${d.leafWord}, authored by the caller, to \`ctx.db.${d.leavesDb}\`, and return it.
  A ${d.leafWord} record has the shape \`{ id, ${d.idArg}, authorId, orgId, body, createdAt }\`.
- Only a member of the ${d.containerWord} may post a ${d.leafWord} on it; otherwise throw an Error.
- If the ${d.containerWord} does not exist, throw an Error.

Return ONLY the JavaScript module code. No prose, no markdown.
`,
};

const UPDATE_PROFILE_SPEC = `Implement updating a user profile.

Write an ES module that exports a function:

  export function updateProfile(ctx, targetUserId, patch) { ... }

- Apply \`patch\` (e.g. \`{ name, bio }\`) to the target user's record in \`ctx.db.users\` and return the
  updated record.
- If the target user does not exist, throw an Error.

Return ONLY the JavaScript module code. No prose, no markdown.
`;

function testsMjs(D) {
  return `// ${GEN.replace('<!-- ', '').replace(' -->', '')}
// Cohesion oracle for the scale-d${D} epic (${D} domain(s) = ${4 * D + 1} surfaces). Thin wrapper over the
// shared, mutation-tested builder in ../../lib/scale-oracle.mjs.
import { buildOracle, domainsFor } from '../../lib/scale-oracle.mjs';

const o = buildOracle(domainsFor(${D}));
export const EXPECTS = o.EXPECTS;
export const happy = o.happy;
export const crosscut = o.crosscut;
export const integration = o.integration;
`;
}

function writeFixture(D) {
  const domains = domainsFor(D);
  const dir = path.join(HERE, 'epics', `scale-d${D}`);
  fs.mkdirSync(path.join(dir, 'surfaces'), { recursive: true });
  fs.writeFileSync(path.join(dir, 'preamble.md'), `${GEN}\n${preamble(domains)}`);
  fs.writeFileSync(path.join(dir, 'skeleton.md'), `${GEN}\n${skeleton(domains)}`);
  fs.writeFileSync(path.join(dir, 'tests.mjs'), testsMjs(D));
  for (const d of domains) {
    fs.writeFileSync(path.join(dir, 'surfaces', `${d.createFn}.md`), surfaceSpec.create(d));
    fs.writeFileSync(path.join(dir, 'surfaces', `${d.listFn}.md`), surfaceSpec.list(d));
    fs.writeFileSync(path.join(dir, 'surfaces', `${d.addMemberFn}.md`), surfaceSpec.addMember(d));
    fs.writeFileSync(path.join(dir, 'surfaces', `${d.postFn}.md`), surfaceSpec.post(d));
  }
  fs.writeFileSync(path.join(dir, 'surfaces', 'updateProfile.md'), UPDATE_PROFILE_SPEC);
  return { D, surfaces: 4 * D + 1, dir: path.relative(path.join(HERE, '..', '..'), dir) };
}

const MAX = Math.min(Number(arg('max', MAX_DOMAINS)) || MAX_DOMAINS, DOMAIN_CATALOG.length);
const made = [];
for (let D = 1; D <= MAX; D++) made.push(writeFixture(D));
for (const m of made) console.log(`wrote ${m.dir}  (${m.surfaces} surfaces)`);
